Repository Curious-Ecosystem/Curious-Connect, pull requests merged in 2024-08, with the labels that each got.

#268 Auto Commenting when a PR is merged
  .github/workflows/auto-comment-pr-merge.yml
Labels: level2, gssoc

#275 Development Name
  README.md
Labels: level3

#276 Development Name
  README.md
Labels: level3

#277 Development Name
  frontend/src/Components/Pages/Landing-Page/Navbar.jsx
Labels: gssoc, level3

#279 Development Name
  README.md
Labels: gssoc, level3

#278 Development Name
  frontend/src/Components/Pages/Landing-Page/Navbar.jsx
Labels: gssoc, level3

#282 Added Contributions by Domeshwer Sahu
  README.md
Labels: gssoc, level3

#284 Contribution Done By Aman Kumar Gupta
  README.md
Labels: gssoc, level3

#234 Implemented meeting backend
  services/Meeting/controllers/meetingController.js
  services/Meeting/index.js
  services/Meeting/models/meetingModel.js
  services/Meeting/routes/meetingRoute.js
Labels: gssoc, level3

#241 #141 Enhance the about us page with more information
  frontend/package.json
  frontend/src/Components/common/Footer/AboutSection/AboutPage.jsx
  frontend/src/assets/About-Page-Assets/chatMsg.svg
  frontend/src/assets/About-Page-Assets/customMeet.svg
  frontend/src/assets/About-Page-Assets/customMeet2.svg
  frontend/src/assets/About-Page-Assets/encrypt.svg
  frontend/src/assets/About-Page-Assets/screenShared.svg
  frontend/src/assets/About-Page-Assets/videoConf.png
  frontend/tailwind.config.js
  package.json
Labels: gssoc, level3

#219 Enchanced about us page and added more faqs.
  frontend/src/Components/common/Footer/AboutSection/AboutPage.jsx
  frontend/src/Components/common/Footer/AboutSection/FAQ.jsx
Labels: level2, gssoc

#218 Added Animated icon in Navbar links
  frontend/index.html
  frontend/src/Components/Pages/Landing-Page/Navbar.jsx
Labels: level2, gssoc

#205 FireBase Added
  frontend/package.json
  frontend/src/Firebase/firebase-config.js
  frontend/src/Pages/Landing-Page.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/custom-hooks/UseAuth.js
Labels: gssoc, level3

#212 flickering fixed
  frontend/src/Components/Pages/Landing-Page/JoinWithCode.jsx
Labels: gssoc, level3

#213 Updated 404 error page
  frontend/src/App.jsx
  frontend/src/Components/Pages/Error-Page/ErrorPage.jsx
  frontend/src/Pages/Error-Page.jsx
  frontend/src/assets/Landing-Page-Assets/ErrorImage.png
Labels: gssoc, level3

#222 Hero section mobile view
  frontend/src/Components/Pages/Landing-Page/HeroSectionMobileView.jsx
  frontend/src/Components/Pages/Landing-Page/Navbar.jsx
  frontend/src/Pages/Landing-Page.jsx
  frontend/src/assets/Landing-Page-Assets/hero-mobile.png
Labels: gssoc, level3

#273 Reduce Hover Speed of button
  desktop.ini
  frontend/src/Components/common/Footer/Footer.jsx
  package.json
Labels: gssoc, level3

#211 fix : change bg color of component & input box
  frontend/src/Components/Pages/Landing-Page/JoinWithCode.jsx
Labels: level1, gssoc

#285 Revert "Development Name"
  README.md
Labels: gssoc, level3

#288 Development Ujjwal
  README.md
Labels: gssoc, level3

#287 Contribution in Curious Connect
  README.md
Labels: gssoc, level3

#289 Development Ujjwal In Readme
  README.md
Labels: gssoc, level3

#286 Features added to chat window
  README.md
Labels: gssoc, level3

#291 Removing all Errors from Curious Connect
  frontend/src/Components/Pages/Landing-Page/JoinWithCode.jsx
  frontend/src/Components/Pages/Landing-Page/Navbar.jsx
  frontend/src/Components/common/Footer/AboutSection/AboutPage.jsx
  package.json
Labels: gssoc, level3

#293 Update Issue Resolved Readme
  README.md
Labels: gssoc, level3
