Repository Curious-Ecosystem/Curious-Connect, pull requests merged in 2024-05, with the labels that each got.

#44 feat: [add JWT authentication middleware]
  package.json
  services/Auth/config.js
  services/Auth/index.js
  services/Auth/src/config/config.db.js
  services/Auth/src/config/config.js
  services/Auth/src/controllers/auth.controller.js
  services/Auth/src/main.js
  services/Auth/src/middleware/auth.middleware.js
  services/Auth/src/models/user.model.js
  services/Auth/src/routes/auth.route.js
  services/Auth/src/utils/error.js
  services/Media/index.js
Labels: CDC-CC-Accepted, level2, gssoc, Branch:feature/InitialUIDesign

#29 feat: [add JWT authentication middleware]
  package.json
  services/Auth/config.js
  services/Auth/index.js
  services/Auth/src/config/config.db.js
  services/Auth/src/config/config.js
  services/Auth/src/controllers/auth.controller.js
  services/Auth/src/main.js
  services/Auth/src/middleware/auth.middleware.js
  services/Auth/src/models/user.model.js
  services/Auth/src/routes/auth.route.js
  services/Auth/src/utils/error.js
  services/Media/index.js
Labels: level2, gssoc

#67 [Footer.jsx] - Footer Component Completed !
  frontend/src/Components/common/Footer.jsx
Labels: CDC-CC-Accepted, CDC-CC-Enhancements, GSoC 2024, level2, gssoc, Branch:main

#76 Meeting Cards updated
  frontend/src/Components/Pages/Landing-Page/MeetingCards.jsx
  frontend/tailwind.config.js
  package.json
Labels: CDC-CC-Accepted, CDC-CC-Valid-Pull-Request, Sprint-1-UIDesign, GSoC 2024, level1, gssoc, GSSOC - High Importance

#77 Added 'About', 'Contact' and 'FAQ' Pages
  frontend/src/App.jsx
  frontend/src/Components/common/Footer/AboutSection/AboutPage.jsx
  frontend/src/Components/common/Footer/AboutSection/Contact.jsx
  frontend/src/Components/common/Footer/AboutSection/FAQ.jsx
  frontend/src/Components/common/Footer/Footer.jsx
  frontend/src/Pages/Landing-Page.jsx
  package.json
Labels: CDC-CC-Accepted, CDC-CC-Enhancements, GSoC 2024, level2, gssoc, GSSOC - High Importance, Branch:main

#85 [Feature.jsx]- Feature cards added
  frontend/src/Components/Pages/Landing-Page/Feature.jsx
Labels: level2, gssoc, GSSOC - High Importance, Branch:main, CDC-CC-Frontend

#87 feat: automate greeting using github action
  .github/workflows/greetings.yml
Labels: GSoC 2024, level2, gssoc, GSSOC - High Importance, Branch:main

#91 [FIX] #83 - Completed the 'Legal Section' of Footer Section
  frontend/src/App.jsx
  frontend/src/Components/common/Footer/Footer.jsx
  frontend/src/Components/common/Footer/LegalSection/PrivacyPolicyPage.jsx
  frontend/src/Components/common/Footer/LegalSection/TermsOfService.jsx
Labels: enhancement, gssoc, GSSOC - High Importance, Branch:main, CDC-CC-Frontend

#102 FIX: Yarn Package Manager
  frontend/package.json
  package.json
  services/Auth/src/controllers/auth.controller.js
  services/Auth/src/main.js
  services/Meeting/package.json
  services/Signaling/index.js
  services/Signaling/package.json
Labels: CDC-CC-Accepted, CDC-CC-Enhancements, level2, gssoc, Branch:main

#97 Fixed the landing page
  frontend/package.json
  frontend/src/Components/Pages/Landing-Page/MeetingCards.jsx
  frontend/src/Pages/Landing-Page.jsx
  package.json
Labels: CDC-CC-Enhancements, GSoC 2024, level2, gssoc, GSSOC - High Importance, Branch:main

#110 Our product UI created
  frontend/src/Components/Pages/Landing-Page/OurTeam.jsx
  frontend/src/assets/Landing-Page-Assets/CDC.jpg
  frontend/src/assets/Landing-Page-Assets/Curious.jpeg
  frontend/src/assets/Landing-Page-Assets/Inspiration.jpg
Labels: level1, gssoc, GSSOC - High Importance

#115 Responsive Header Fixed
  frontend/src/Components/Pages/Landing-Page/LandingHeader.jsx
  frontend/src/Pages/Landing-Page.jsx
  frontend/src/assets/Header/home-r.png
  frontend/src/assets/Header/refresh.png
  frontend/tailwind.config.js
Labels: level2, gssoc

#111 [Issue #81] Error handled in Auth signup and signin and tested - Fixed issues in last commit
  services/Auth/src/controllers/auth.controller.js
  services/Auth/src/models/user.model.js
Labels: CDC-CC-Accepted, level2, gssoc, CDC-CC-Backend

#132 Enhanced hero section !
  frontend/src/Components/Pages/Landing-Page/HeroSection.jsx
  frontend/src/Components/Pages/Landing-Page/JoinWithCode.jsx
  frontend/src/index.css
Labels: GSoC 2024, level2, gssoc, GSSOC - High Importance, CDC-CC-Frontend

#136 [issueReminder.yml]-Issue reminder added #106
  .github/workflows/issueReminder.yml
Labels: CDC-CC-Accepted, gssoc, level3, GSSOC - High Importance

#130 feat: add real-time chat functionality with Express and Socket.IO
  package.json
  services/Signaling/index.js
  services/Signaling/package.json
Labels: CDC-CC-Accepted, gssoc, level3, Branch:main, CDC-CC-Backend

#137 [FEATURE] Created the 'Create Meeting' Page
  D
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Components/Pages/Landing-Page/MeetingCards.jsx
  frontend/src/Components/Pages/Meeting-Page/Create-Meeting.jsx
  frontend/src/Components/Pages/Meeting-Page/Meeting-Details.jsx
  frontend/src/Components/Pages/Meeting-Page/Sidebar.jsx
  frontend/src/Components/common/Footer/LegalSection/PrivacyPolicyPage.jsx
  frontend/src/Pages/Create-Meeting-Page.jsx
  frontend/tailwind.config.js
  package.json
Labels: CDC-CC-Accepted, gssoc, level3, GSSOC - High Importance, Branch:main, CDC-CC-Backend, CDC-CC-Frontend

#139 [Issue #105] [Formatting] - add .Prettier for formatting the code into proper tabspaces and indentation
  .prettierignore
  .prettierrc
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Components/Pages/Join-Room-Page/JoinRoom.jsx
  frontend/src/Components/Pages/Landing-Page/FeatureCardSection.jsx
  frontend/src/Components/Pages/Landing-Page/HeroSection.jsx
  frontend/src/Components/Pages/Landing-Page/JoinWithCode.jsx
  frontend/src/Components/Pages/Landing-Page/MeetingCards.jsx
  frontend/src/Components/Pages/Landing-Page/OurProducts.jsx
  frontend/src/Components/Pages/Meeting-Page/Create-Meeting.jsx
  frontend/src/Components/Pages/Meeting-Page/Meeting-Details.jsx
  frontend/src/Components/Pages/Meeting-Page/Sidebar.jsx
  frontend/src/Components/common/Footer/AboutSection/AboutPage.jsx
  frontend/src/Components/common/Footer/AboutSection/Contact.jsx
  frontend/src/Components/common/Footer/AboutSection/FAQ.jsx
  frontend/src/Components/common/Footer/Footer.jsx
  frontend/src/Components/common/Footer/LegalSection/PrivacyPolicyPage.jsx
  frontend/src/Components/common/Footer/LegalSection/TermsOfService.jsx
  frontend/src/Components/common/SignIn.jsx
  frontend/src/Components/common/SignUp.jsx
  frontend/src/Components/core/authModalSteps/AuthModal.jsx
  frontend/src/Constants/country-code.jsx
  frontend/src/Data/navigation-data.jsx
  frontend/src/Pages/Create-Meeting-Page.jsx
  frontend/src/Pages/JoinRoom-Page.jsx
  frontend/src/Pages/Landing-Page.jsx
  frontend/src/Pages/SignIn-Page.jsx
  frontend/src/Pages/SignUp-Page.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  package.json
Labels: CDC-CC-Good-First-Issue, level2, gssoc, GSSOC - High Importance, Branch:main

#145 add_issue_templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/document.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/refactor_code.yml
  .github/ISSUE_TEMPLATE/task-request.md
  .github/ISSUE_TEMPLATE/task-request.yml
Labels: gssoc, level3, GSSOC - High Importance

#144 [UI Enhancements] - Features Card Enhance the Features Card for curious connect
  frontend/src/Components/Pages/Landing-Page/FeatureCardSection.jsx
Labels: CDC-CC-Accepted, CDC-CC-Enhancements, gssoc, level3, GSSOC - High Importance, Branch:main, CDC-CC-Frontend

#156 Update App.jsx
  frontend/src/App.jsx
Labels: level1, gssoc

#157 Update MeetingCards.jsx
  frontend/src/Components/Pages/Landing-Page/MeetingCards.jsx
Labels: level1, gssoc

#158 Update Create-Meeting.jsx
  frontend/src/Components/Pages/Meeting-Page/Create-Meeting.jsx
Labels: level2, gssoc

#159 Update Meeting-Details.jsx
  frontend/src/Components/Pages/Meeting-Page/Meeting-Details.jsx
Labels: level2, gssoc

#160 Update Sidebar.jsx
  frontend/src/Components/Pages/Meeting-Page/Sidebar.jsx
Labels: level2, gssoc

#150 [FEATURE] Completed 'Availability' Section in 'Create Meeting' Page
  frontend/package.json
  frontend/src/Components/Pages/Meeting-Page/Meeting-Availability.jsx
Labels: CDC-CC-Accepted, CDC-CC-Enhancements, level3, GSSOC - High Importance, Branch:main

#164 [UI Enhancement ] Faq section is Accordion component
  frontend/src/Components/common/Footer/AboutSection/FAQ.jsx
Labels: level2, gssoc, Branch:main, CDC-CC-Frontend

#174 [Enhancement] - The privacy and policy page
  frontend/src/Components/common/Footer/LegalSection/PrivacyPolicyPage.jsx
Labels: enhancement, CDC-CC-Enhancements, gssoc, level3

#183 [issueReminder.yml]- bug fix
  .github/workflows/issueReminder.yml
Labels: CDC-CC-Accepted, CDC-CC-Enhancements, gssoc, level3

#181 [FIX #177] Implemented Backend Integration
  frontend/package.json
  frontend/src/Components/Pages/Meeting-Page/Meeting-Availability.jsx
  frontend/src/Components/Pages/Meeting-Page/Meeting-Details.jsx
  frontend/src/Components/Pages/Meeting-Page/Sidebar.jsx
  services/Meeting/index.js
  services/Meeting/package.json
Labels: CDC-CC-Accepted, gssoc, level3, CDC-CC-Backend

#172 Card Section Updated
  frontend/src/Components/Pages/Landing-Page/FeatureCardSection.jsx
Labels: level2, gssoc, level3

#171 feat:responsive navbar
  frontend/src/App.jsx
  frontend/src/Components/Pages/Landing-Page/Navbar.jsx
  frontend/src/Pages/Landing-Page.jsx
  package.json
Labels: level2, gssoc

#209 Update Contact.jsx Second Time after Fixing Submit Button
  frontend/src/Components/common/Footer/AboutSection/Contact.jsx
Labels: level2, gssoc

#207 Added contributors list
  README.md
Labels: level2, gssoc

#204 Issue#90: Made a postman collection for auth apis in apiInfo
  apiInfo/Curious Connect.postman_collection.json
Labels: gssoc, level3

#198 [bug fixed: Added Direct Links to Homepage]
  frontend/src/Components/common/Footer/Footer.jsx
  frontend/src/Components/common/Footer/LegalSection/TermsOfService.jsx
Labels: level1, gssoc

#168 privacy policy page enhancement
  frontend/src/Components/common/Footer/LegalSection/PrivacyPolicyPage.jsx
Labels: gssoc, level3

#223 Fixes: #206 Enhanced_readme
  README.md
Labels: level1, gssoc

#220 Update PrivacyPolicyPage With Animations And Hovering Effects
  frontend/src/Components/common/Footer/LegalSection/PrivacyPolicyPage.jsx
Labels: gssoc, level3

#221 Update TermsOfService With Animations and Fixes Bugs
  frontend/src/Components/common/Footer/LegalSection/TermsOfService.jsx
Labels: gssoc, level3

#226 Made Join with code section responsive
  frontend/src/Components/Pages/Landing-Page/JoinWithCode.jsx
Labels: level2, gssoc

#230 Enhance FAQ Section Frontend Flexibility
  frontend/src/Components/common/Footer/AboutSection/FAQ.jsx
Labels: level2, gssoc

#238 Enhance Feature Card Section with Animations Using Framer Motion
  frontend/src/Components/Pages/Landing-Page/FeatureCardSection.jsx
Labels: gssoc, level3

#236 [Issue #166] Cookie implementation in signup and signin #gssoc24
  services/Auth/package.json
  services/Auth/src/controllers/auth.controller.js
Labels: gssoc, level3

#237 Enhancing the HeroSection With Fixing Minor Issues and making It Dynamic
  frontend/src/Components/Pages/Landing-Page/HeroSection.jsx
Labels: gssoc, level3

#216 Update AboutPage With Framer Motion, React Icons
  frontend/src/Components/common/Footer/AboutSection/AboutPage.jsx
Labels: level2, gssoc

#185 Added and Corrected the Initial Files of the Zod
  services/Auth/package.json
  services/Auth/src/controllers/auth.controller.js
  services/Auth/src/middleware/validate.schema.js
  services/Auth/src/routes/auth.route.js
  services/Auth/src/validation/zodschema.js
Labels: gssoc, level3, CDC-CC-Backend

#244 Enhance OurProducts Section With Text Motion, Animation And Fixes Minor Issue
  frontend/src/Components/Pages/Landing-Page/OurProducts.jsx
Labels: level2, gssoc

#228 Added favicon
  frontend/index.html
Labels: level1, gssoc
